# Generated by Django 4.2.10 on 2024-07-29 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sec_phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
