# Generated by Django 4.2.10 on 2024-08-26 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_printed',
            field=models.BooleanField(default=False),
        ),
    ]
