# Generated by Django 5.1.1 on 2024-12-17 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_email_code_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='update_times',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
