# Generated by Django 5.1.1 on 2024-12-17 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_order_update_times'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='pickup_date',
        ),
    ]
