# Generated by Django 5.1.1 on 2024-12-18 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_user_can_post_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_code_expires_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_code_expires_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
