# Generated by Django 5.1.1 on 2024-12-19 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_user_email_code_expires_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='phone_code_expires_at',
            new_name='password_code_expires_at',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='phone_verification_code',
            new_name='password_reset_code',
        ),
    ]
