# Generated by Django 4.2.10 on 2024-08-29 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shopping', '0006_rename_height_articlespecification_heigth'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='banner_article_imgs/')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.article')),
            ],
        ),
    ]
