# Generated by Django 4.2.10 on 2024-09-02 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contactmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmessage',
            old_name='name',
            new_name='user',
        ),
    ]
