# Generated by Django 5.1.1 on 2024-12-17 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_bannerarticle_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerarticle',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
