# Generated by Django 5.1.1 on 2024-12-28 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AndroidApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(help_text='Version of the Android app (e.g., 1.0.0)', max_length=20)),
                ('apk_file', models.FileField(blank=True, help_text='Upload the APK file', null=True, upload_to='apk_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
