# Generated by Django 4.2.10 on 2024-07-30 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_articlespecification_article_specification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shopping.brand'),
        ),
    ]
