# Generated by Django 4.2.10 on 2024-08-20 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0005_article_extra_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlespecification',
            old_name='height',
            new_name='heigth',
        ),
    ]
