# Generated by Django 4.2.10 on 2024-08-31 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0006_rename_height_articlespecification_heigth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='retail_price',
            new_name='detail_price',
        ),
        migrations.AddField(
            model_name='article',
            name='deal_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='discounted_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
